#! /bin/sh
#
# Install opam, ocaml compilers and standard library.
# From https://github.com/mjambon/setup-ocaml
#
set -eu

mkdir -p .ssh
chmod 700 .ssh

git config --global user.email "docker@example.com"
git config --global user.name "Docker"

opam init --disable-sandboxing
opam switch create "$@"

cat >> ~/.bashrc <<"EOF"
# From https://github.com/mjambon/ocaml-layer
echo 'Running "eval $(opam env)", which initializes PATH and other variables.'
echo
echo 'In scripts and dockerfiles, don't forget to run your commands as
echo '  opam exec -- COMMAND'
echo 'or equivalently as'
echo '  eval $(opam env) && COMMAND'
echo
eval $(opam env)
EOF
