#! /usr/bin/env bash
#
# Push Docker images to Docker Hub.
# This pushes the images created with './docker-build' and stored to a
# temporary file.
#
# From https://github.com/mjambon/setup-ocaml
#
# Usage: ./docker-push
#
#
set -eu

for docker_url in $(cat pushme); do
  echo "Pushing '$docker_url'."
  docker push "$docker_url"
done
