#! /usr/bin/env bash
#
# Build or update Docker images locally.
# From https://github.com/mjambon/setup-ocaml
#
# Usage: ./docker-build [CONFIG_FILE1 CONFIG_FILE2 ...]
#
# Each config file is used separately to build a Docker image.
# If no argument is given, a single config file 'config.sh' is assumed.
#
set -eu

# Defaults
os="alpine"
from="alpine:3.12.0"
docker_url="mjambon/ocaml:alpine"
user="user"
extra_packages=""
opam_switch="4.10.0"
opam_packages="dune utop"

# Override defaults.
configs="config.sh"

if [[ $# -gt 0 ]]; then
  configs=$*
fi

build() {
  (
    if [[ -f "$config" ]]; then
      echo "Build from config '$config'."
      . ./"$config"
    else
      echo "Build with default settings."
    fi

    rm -rf tmp
    mkdir -p tmp

    mkdir -p tmp/os
    cp -a src/os/"$os" tmp/os
    cp -a src/opam tmp
    cp -a src/create-dockerfile tmp

    (
      cd tmp
      ./create-dockerfile -o Dockerfile \
        --os "$os" \
        --from "$from" \
        --create-user "$user" \
        --extra-packages "$extra_packages" \
        --opam-packages "$opam_packages" \
        --opam-switch "$opam_switch"
      docker build -t "$docker_url" .

      # Sanity check.
      docker run -t "$docker_url" opam exec -- ocamlc -v
    )
  )
}

for config in $configs; do
  build
done
