#! /usr/bin/env bash
#
# Create a non-privileged user on Alpine.
#
set -eu

error() {
  echo "Error: $*" >&2
  exit 1
}

[[ $# = 1 ]] || error "Exactly one argument is expected, a user name."

user="$1"
echo "Creating user '$user'"

adduser -S -u 1000 -g 1000 "$user"
echo '"$user" ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/"$user"
chmod 440 /etc/sudoers.d/"$user"
chown root:root /etc/sudoers.d/"$user"
sed -i.bak 's/^Defaults.*requiretty//g' /etc/sudoers
