#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout

      # Work around "no docker within no docker".
      - setup_remote_docker

      - run:
          name: Build
          command: make build
      - run:
          name: Login
          command: ./.circleci/docker-login
      - run:
          name: Push
          command: make push

  build-only:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout

      # Work around "no docker within no docker".
      - setup_remote_docker

      - run:
          name: Build
          command: make build

workflows:
  version: 2

  build-on-push:
    jobs:
      - build-only

  build-and-push-weekly:
    # Rebuild periodically rather than based on git changes.
    triggers:
      - schedule:
          # Run at 11:00 every Wednesday, UTC.
          cron: "0 11 * * 3"
          filters:
            branches:
              only:
                - master
                - main

    jobs:
      - build-and-push:
          # Run only on these branches (each pushing different images)
          filters:
            branches:
              only:
                - master
                - main
