#! /bin/sh
#
# General system setup for Alpine Linux prior to installing Opam.
# From https://github.com/mjambon/setup-ocaml
#
set -eu

echo '@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' \
     >> /etc/apk/repositories

apk update
apk upgrade

packages="
  bash
  bubblewrap
  build-base
  bzip2
  ca-certificates
  coreutils
  curl
  git
  libx11-dev
  m4
  nano
  ncurses-dev
  opam
  openssl
  patch
  rsync
  sudo
  tar
  xz
"

apk add $packages

git config --global user.email "docker@example.com"
git config --global user.name "Docker"
