#! /bin/sh
#
# General system setup for Alpine Linux prior to installing Opam.
# From https://github.com/mjambon/setup-ocaml
#
set -eu

# The command line arguments are a list of extra packages to install.
extra_packages=$*

echo '@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing' \
     >> /etc/apk/repositories

packages="
  bash
  bubblewrap
  build-base
  bzip2
  ca-certificates
  coreutils
  curl
  git
  libx11-dev
  m4
  nano
  ncurses-dev
  opam
  openssl
  patch
  pre-commit
  py-pip
  rsync
  sudo
  tar
  xz
  $extra_packages
"

# can't have --no-cache here because https://github.com/ocaml/opam/issues/5186
apk add $packages

if [ -z "$(git config user.email)" ]; then
  git config --global user.email "docker@example.com"
  git config --global user.name "Docker"
fi
